CREATE TABLE Customer
(customer_id INT GENERATED BY
DEFAULT AS IDENTITY PRIMARY KEY,
fname VARCHAR(255),
lname VARCHAR(255),
e_mail VARCHAR(255)
);

CREATE TABLE category
(category_id INT GENERATED
BY DEFAULT AS IDENTITY PRIMARY
KEY,
name VARCHAR(255) );

CREATE TABLE address
(address_id INT GENERATED BY
DEFAULT AS IDENTITY PRIMARY KEY,
customer_id INT REFERENCES
"Customer"(customer_id),
street VARCHAR(255),
city VARCHAR(255),
post_code INT);

CREATE TABLE Product
( product_id INT GENERATED BY
DEFAULT AS IDENTITY PRIMARY KEY,
product_name VARCHAR(255),
description VARCHAR,
price NUMERIC,
stock INTEGER,
seller_id INT REFERENCES
"Seller"(seller_id),
category_id INT REFERENCES
category(category_id) );

CREATE TABLE Order
(order_id INT GENERATED BY DEFAULT
AS IDENTITY PRIMARY KEY,
customer_id INT REFERENCES
"Customer"(customer_id),
order_date DATE DEFAULT CURRENT_DATE,
address_id INT REFERENCES address
(address_id),
order_status_id INT REFERENCES
order_status(order_status_id),
total_amount NUM);

CREATE TABLE order_item
( item_id INT GENERATED BY
DEFAULT AS IDENTITY PRIMARY
KEY,
order_id INT REFERENCES
"Order"(order_id),
product_id INT REFERENCES
Product"(product_id),
quantity INT,
unit_price NUM);

CREATE TABLE order_status
(order_status_id INT
GENERATED BY DEFAULT AS
IDENTITY PRIMARY KEY,
created_at DATE DEFAULT
CURRENT_DATE,
 status_name VARCHAR(255));

